# Generated by Django 3.2.12 on 2022-03-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_alter_file_imageart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterField(
            model_name='file',
            name='imageArt',
            field=models.ImageField(upload_to='media'),
        ),
    ]
